languageCode = "en-us"
title = "Visualization Snacks"
theme = ["559Theme","roadster"]

# baseURL must be set by the CLI options!
#baseURL = ""
# these old options are leftover from superstition
#relativeURLs = true
#canonifyURLs = true
enableGitInfo = true

# unsafe, but useful...
enableInlineShortcodes = true

# a basic menu
[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -1000
[[menu.main]]
    identifier = "snacks"
    url = "/snacks/"
    name = "Snacks"
    weight = 1
[[menu.main]]
    identifier = "tutorials"
    url = "/tutorials/"
    name = "Tutorials"
    weight = 2
[[menu.main]]
    identifier = "papers"
    url = "/papers/"
    name = "Papers"
    weight = 3
[[menu.main]]
    identifier = "critiques"
    url = "/critiques/"
    name = "Critiques"
    weight = 3
[[menu.main]]
    identifier = "resources"
    url = "/resources/"
    name = "Resources"
    weight = 3
[[menu.main]]
    identifier = "about"
    url = "/about/"
    name = "About"
    weight = 10

[Params]
subtitle = "Visualization Knowledge in Bite-Sized Pieces"
post_meta = ["section","date","taglist","categories"]
dateformat = "January 2, 2006"
copyright = "Michael Gleicher. Using a CC-BY-NC-SA license"
copyrightDate = "2024"

# ImportantPages = ["getting-started","schedule","policies", "communications", "pages/parts-of-class", "syllabus","vis", "exercises","all-readings", "allpages"]
ImportantPages = ["/","1-what-is-vis","allpages"]
ImportantPagesTitle = "Recommended Starting Points"
thisweek = "this00.md"
themestyle = "new"
recentSections = ["snacks","tutorials", "critiques", "papers", "resources"]
mainSections = ["snacks","tutorials", "critiques", "papers", "resources"]
# this needs to be a SITE variable (for list.html)
# this was depricated in Hugo 128
# paginate = 15
[pagination]
  pagerSize = 15

[Params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["lunr","snackguide","important","links","recents","categories","taglist"]

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    codeFences = true
    lineNos = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

[build]
    publishResources = false
